# Site settings
title: Elena's Blog
email: elenasharma3@gmail.com
description: "Thoughts of a web developer-in-training."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: 300watts
github_username:  elenasharma

# Build settings
markdown: kramdown
permalink: pretty
